default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: to_do_list_development
  username: postgres
  password: 123
  host: localhost
  port: 5432

test:
  <<: *default
  database: to_do_list_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
